name: clang-tests-arm
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
    - uses: egor-tensin/setup-clang@v1
      with:
         version: latest
    - name: run Tests
      run: |
          git clone https://github.com/google/googletest 
          cd googletest && mkdir build && cd build 
          cmake ../ 
          make 
          cd ../../ 
          mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=clang++ ..
          make 
          ctest