name: gcc-tests-x86
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run Tests
      run: | 
          git clone https://github.com/google/googletest 
          cd googletest && mkdir build && cd build 
          cmake ../ 
          make 
          cd ../../ 
          mkdir build && cd build && cmake ..
          make 
          ctest
